### ISSUE TITLE
2021 -> Season 20 Episode 21

### ISSUE THREAD

**Issue by artemoo** [tregusti/episode-parser#23]
```
var parser = require('episode-parser')
var filename = 'Secret Magic Control Agency 2021 720p WEBRip 800MB x264-GalaxyRG '
var result = parser(filename)
console.log(result.show) //= 'Secret Magic Control Agency'
console.log(result.season) //= 20
console.log(result.episode) //= 21
```

**Comment by tregusti** [comment]
Yes, that is the result. If you have a bug report please state the desired outcome.

The format of your string is not very structured though.

**Comment by artemoo** [comment]
https://www.imdb.com/title/tt13932162/

This is a movie and this is the title on the torrent.
What does it represent a year as a season and a episode.

**Comment by artemoo** [comment]
All torrents have this file name.

`Colors of Love 2021 720p WEBRip 800MB x264-GalaxyRG`
`Things Heard and Seen 2021 720p WEBRip 800MB x264-GalaxyRG`
`Cornered 2021 720p WEBRip 800MB x264-GalaxyRG`

**Comment by tregusti** [comment]
This package handles episodes. Of series. If does not handle movies.
