### ISSUE TITLE
Unrecognized string

### ISSUE THREAD

**Issue by niicojs** [tregusti/episode-parser#5]
I'll drop this here in case you still work on this.
I'm using your lib to auto subtitle renaming.
Here is an example that's not been recognized: Mr. TvShow - 02x03 - eps2.1k3rnel-pan1c.ksd.KILLERS.English.C.updated.bla.bla

**Comment by tregusti** [comment]
The only thing that would be possible to parse is the show name and the season and number.

To my eye, the episode name is just random stuff without order? Hard to know how to parse.

Sorry for not responding, didn't see the comment.

**Comment by niicojs** [comment]
Show Name, Season and Number is enough. That's how you're sure it's unique anyway.
This show has some pretty garbage episode name I agree :)

**Comment by tregusti** [comment]
Well, I'r really busy right now, I will not have any time before xmas for this. Please create a PR if you want it fixed sooner. As long as you add a test for the string I'm satisfied.
